// ─────────────────────────────────────────────────────────────────────────
// Single source of truth for site identity, SEO, and authorship.
//
// ⚠️ AUTHOR.name was inferred from the account email. If it is wrong, change it
//    HERE ONLY — every byline, About bio, and schema author propagates from this.
// ─────────────────────────────────────────────────────────────────────────

export const SITE = {
  name: 'Devception',
  url: 'https://devception.xyz',
  title: 'Devception — Multiplayer Social Deduction Coding Game',
  description:
    'Devception is a multiplayer social deduction coding game. Collaborate on real programming challenges with 4–8 players while secretly hunting an imposter hidden among the team. Code together. Find the imposter. Trust no one.',
  // Square SVG logo (used in Organization / Article publisher schema).
  logo: 'https://devception.xyz/logo.svg',
  // 1200×630 PNG generated by src/app/opengraph-image.tsx.
  ogImage: 'https://devception.xyz/opengraph-image',
  founded: '2026',
} as const;

export const AUTHOR = {
  name: 'Diwanshu Gupta',
  role: 'Founder & Lead Developer',
  // Human, first-person-credible bio for E-E-A-T (blog byline + About page).
  bio: 'Diwanshu Gupta is the founder and lead developer of Devception. He works mostly in the messy intersection of real-time systems, game design, and developer tooling — and built Devception to make practicing code feel like a team sport instead of a solo grind.',
  url: 'https://devception.xyz/about',
} as const;

// Real, public links ONLY. Leave entries out until they genuinely exist —
// shipping placeholder/dead social links is a trust signal Google penalises.
export const SOCIAL: { label: string; href: string }[] = [];

// Contact route used wherever we previously linked to a (non-existent) Discord/GitHub.
export const CONTACT_URL = '/contact';
